### PR TITLE
docs: add custom server documentation

### PR DESCRIPTION
**Pull request by theomjones**
Adding some preliminary documentation around custom servers with TypeScript.

Let me know your thoughts :)

### CODE REVIEW

**Comment by pi0** [comment]
Custom server for nuxt is highly discouraged and it is suggested to use separate API or server middleware. Even if we are adding this section, this note should be highlighted to use with caution.

**Comment by kevinmarrec** [comment]
I think custom server shouldn't be in TS docs.
Only `tsc` / compilation for runtime is missing in docs I think.

**Comment by theomjones** [comment]
@pi0 
> Custom server for nuxt is highly discouraged and it is suggested to use separate API or server middleware. Even if we are adding this section, this note should be highlighted to use with caution.

Happy to close this PR then. 

For our case, a custom server is unavoidable because we are using [new relic](https://newrelic.com/) which needs to be `require`d before any other JS module. AFAIK there's no other way of doing this without a custom server.

**Comment by pi0** [comment]
@theomjones, would you please open an issue regarding new relic in nuxt repo? I would like to help making it possible.

**Comment by theomjones** [comment]
> @theomjones, would you please open an issue regarding new relic in nuxt repo? I would like to help making it possible.

Sure here you go. Let me know if I can help at all.
https://github.com/nuxt/nuxt.js/issues/6236

**Pull request closed without merging**
