### PR TITLE
docs: Full brazilian portuguese translation

### PR DESCRIPTION
**Pull request by rodgeraraujo**
Added full Brazilian Portuguese translation to docs

Note
You will need some revisions before releasing this.

### CODE REVIEW

**Comment by kevinmarrec** [comment]
Hey @rodgeraraujo , nice work, but seems there is some `cookbook copy` folder, looks like a mistake.

**Comment by rodgeraraujo** [comment]
Hi @kevinmarrec, thanks for that! I see this too and some other "bugs" on my translation, I will fix this and submit with new changes!

**Comment by kevinmarrec** [comment]
@rodgeraraujo Cool awesome !

**Comment by rodgeraraujo** [comment]
Hi @kevinmarrec, I update the pr, please review and thanks!

**Comment by kevinmarrec** [comment]
Hey @rodgeraraujo , you need to update Vuepress config like here: https://github.com/nuxt/typescript/compare/spanish-translation?expand=1#diff-d669c10d59b56bb12a815dd48ce8d884 to correctly have access on the translated pages.

You can then check Netlify Preview after commiting to check everything is ok.

**Comment by kevinmarrec** [comment]
I'm gonna finish the remaining things on a new branch then merge in master.

**Comment by rodgeraraujo** [comment]
@kevinmarrec  thanks for finish!

**Pull request merged**
