### PR TITLE
fix(types): add functions and arrays for postcss plugins

### PR DESCRIPTION
**Pull request by danielroe**

### CODE REVIEW

**Comment by kevinmarrec** [comment]
@danielroe Tests failed but that's actually weird, it seems to have fail after the merge and the only thing I did is lock file maintenance. Seems there have been something changed around `postcss` types then.

**Comment by danielroe** [comment]
@kevinmarrec Sorry, only just saw this!

**Comment by kevinmarrec** [comment]
Oh it seems it's cause CircleCI only runs on `master`, that's why it only failed when merged 😅

**Comment by danielroe** [comment]
@kevinmarrec Want me to set us up on GH actions?

**Comment by kevinmarrec** [comment]
@danielroe Sounds good to me yeah, I still didn't take time to try it :D

**Pull request merged**
