### PR TITLE
fix(types): use connect type for server middleware

### LINKED ISSUE #183: Wrong type for ServerMiddleware
**Describe the bug**
`ServerMiddleware` is defined as an alias of `RequestHandler` from `express`. However, if you try to use for example the function `req.send`, which is available according to the types, it will fail.

**To Reproduce**
1. Create this function as a serverMiddleware:
```
    (req, res) => {
      res.send('OK')
    }
```

2. Make a request to the server and observe that you get the error "res.send is not a function".

**Expected behavior**
The types should not include functions which don't exist in runtime. I'm not sure what the correct type is though, maybe `RequestListener` from `http`.

**Additional context**
Versions:
nuxt: 2.10.2
@nuxt/typescript-build: 0.3.3
@nuxt/typescript-runtime: 0.2.3

### PR DESCRIPTION
**Pull request by danielroe**
closes #183

(if you haven't already been working on this)

### CODE REVIEW

**Comment by trygveaa** [comment]
You should probably remove `@types/express` from `package.json` too? It's not used anywhere anymore.

**Comment by kevinmarrec** [comment]
@trygveaa You're right, it is also a dependency of `@types/compression` : https://github.com/nuxt/typescript/blob/master/yarn.lock#L2176 so it can be safely removed from `package.json`

**Comment by trygveaa** [comment]
@kevinmarrec: Why does it matter if it's a dependency of `@types/compression` when it isn't used?

**Comment by kevinmarrec** [comment]
@trygveaa I meant even if it was used it could have been omitted from `package.json` as `@types/compression` would install it anyways :)

I've local changes ready but there's an issue regarding a package (https://github.com/zloirock/core-js/issues/711) which is buggy until NPM registry is correctly updated, so i'm just waiting a bit to have the lock file maintnance as well to have `yarn.lock` clean after removal.

**Comment by kevinmarrec** [comment]
Done (https://github.com/nuxt/typescript/commit/31108af40be943db05f02522ab75aac4af3674ad)

**Pull request merged**
