### PR TITLE
ci: add github actions workflow

### PR DESCRIPTION
**Pull request by danielroe**
This will need the creation of a `CODECOV_TOKEN` secret via Settings ... Secrets.

### CODE REVIEW

**Comment by danielroe** [comment]
I think this will need to be merged into a branch in `nuxt/typescript` repo before we can really test it.

**Comment by danielroe** [comment]
See https://github.com/danielroe/typescript/commit/6186df6aea9b25291167c3a370eb5257f1c23e8a/checks?check_suite_id=338420231 for sample output.

**Comment by kevinmarrec** [comment]
@danielroe Are you sure a Codecov token is required ? I don't see any token for CircleCI

**Comment by danielroe** [comment]
@kevinmarrec I've not used Codecov before, but this is the message I get in my fork's workflow:

```
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/runner/work/typescript/typescript -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/runner/work/typescript/typescript/coverage/lcov.info
    + /home/runner/work/typescript/typescript/coverage/clover.xml
==> Uploading reports
    HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

**Comment by kevinmarrec** [comment]
@danielroe Yeah I think it's around Codecov itself that the repo is linked by its name, gonna merge this and see what happens

**Pull request merged**
