### PR TITLE
fix: add babel preset types for function argument

### PR DESCRIPTION
**Pull request by danielroe**
closes [#6691](https://github.com/nuxt/nuxt.js/issues/6691)

### CODE REVIEW

**Comment by kevinmarrec** [comment]
@danielroe Could you please share your findings (https://github.com/nuxt/nuxt.js/issues/6691#issuecomment-553284418) ? So I can see how you ended up with these changes ? :)

**Comment by danielroe** [comment]
@kevinmarrec Sure. I'll dig out the relevant lines in the nuxt codebase. But for a quick & dirty, just try compiling with the following `nuxt.config`:

```js
export default {
  build: {
    babel: {
      presets: context => console.log(context)
    }
  }
};
```

**Comment by danielroe** [comment]
See:
* [this](https://github.com/nuxt/nuxt.js/blob/de934844e2c12a2383c2a7ab2d3b43b0b9c8180e/packages/webpack/src/config/base.js#L108) is where `presets()` is called
* [here](https://github.com/nuxt/nuxt.js/blob/de934844e2c12a2383c2a7ab2d3b43b0b9c8180e/packages/webpack/src/config/base.js#L36) is the definition of `this.nuxtEnv` which is passed to `presets()`

**Comment by kevinmarrec** [comment]
Thanks @danielroe , well it seems to be a bit redundant with https://github.com/nuxt/typescript/blob/master/packages/types/config/module.d.ts#L11 but I think it's different context object

**Comment by kevinmarrec** [comment]
So I think it's fine for now, dunno

**Comment by danielroe** [comment]
@kevinmarrec I agree. I'd merge them if they were being set from a central place but as far as I can tell they are completely independent of each other in the Nuxt codebase.

**Comment by kevinmarrec** [comment]
@danielroe Yeah alright

**Comment by danielroe** [comment]
Done. And also in the other two PRs outstanding.

**Pull request merged**
