### PR TITLE
docs: request pollution issue has been fixed on vuex-module-decorators

### PR DESCRIPTION
**Pull request by championswimmer**
PR has been merged https://github.com/championswimmer/vuex-module-decorators/pull/157

### CODE REVIEW

**Comment by danielroe** [comment]
@championswimmer I think it makes sense to wait for the release, as the security issue will continue to affect users until that point.

**Comment by kevinmarrec** [comment]
@danielroe Seems to have been released isn't it ?
image

**Comment by danielroe** [comment]
@championswimmer @kevinmarrec My apologies! I was watching for release but completely missed it. :man_facepalming:

**Comment by kevinmarrec** [comment]
No problem @danielroe

**Pull request merged**
