### PR TITLE
Middleware has to return a async function

### PR DESCRIPTION
**Pull request by thelfensdrfer**

### CODE REVIEW

**Comment by danielroe** [comment]
Could you explain more?

**Comment by thelfensdrfer** [comment]
Sure. Since 2/3 years non promise based return values are deprecated: https://github.com/nuxt/nuxt.js/issues/4158

Without this fix my nuxt project throws errors.

**Comment by danielroe** [comment]
@thelfensdrfer Middleware doesn't need to be an async function. Though of course it can be. The issue you've linked is just indicating that it shouldn't take a callback function as a second argument.

```js
// This is fine
const myMiddleware: Middleware = (context) => {}

// This is not
const myMiddleware: Middleware = (context, callback) => {}
```

**Comment by thelfensdrfer** [comment]
Sorry, you are completely right. I tested it with and without promises and everything stays the same. It had to be something else.

**Pull request closed without merging**
